[build]
  command = "true"
  publish = "."
  https://app.netlify.com/projects/final-desarrollo-web/overview
6c9c1d44-2d38-407b-976b-82596012586a
[![Netlify Status](https://api.netlify.com/api/v1/badges/6c9c1d44-2d38-407b-976b-82596012586a/deploy-status)](https://app.netlify.com/projects/final-desarrollo-web/deploys)
